### ISSUE TITLE
这个库是一个隐藏的炸弹。

### ISSUE THREAD

**Issue by Randy1993** [faimin/ZDToolKit#1]
导入这个库之后，所有的点击事件延迟，Tabbar无法点击，找了半天的bug，发现不用这个库之后就没问题了。

**Comment by faimin** [comment]
这个库目前只是本人对做项目和平时所用方法函数的一些总结和收藏，里面的文件和方法还在一直变化，其实这个属于我自娱自乐的项目😂。
说实话我都没想到会有其他人会使用这个库，对给你造成的麻烦表示歉意，也多谢你提`issue`给我。
如果你想使用的话，推荐`Git`方式引用 `pod 'ZDToolKit', :git => 'https://github.com/faimin/ZDToolKit` ，这样可以引用到最新的代码。你所说的这个问题早已经解决了，只是新版本还没有推到`pod`上去。
